### PR TITLE
Fix dump loading progress indicator for ClassicDumpFormat

### LINKED ISSUE #905: Dump loading progress indicator is broken

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
- fixes #905 including "test"
- adds default fallback implementation for ProgressListener which ignores eta to allow creation of listeners as lambda

### CODE REVIEW

File: chunky/src/java/se/llbit/chunky/renderer/renderdump/ClassicDumpFormat.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ public void readSamples(DataInputStream inputStream, Scene scene, PixelConsumer
         g = inputStream.readDouble();
         b = inputStream.readDouble();
         consumer.consume(pixelIndex, r, g, b);
-        pixelProgress.accept(pixelIndex);
+        pixelProgress.accept(progress++);
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/renderer/renderdump/ClassicDumpFormat.java:46]: Looks like the warning in line 38 also applies to the progress :smile:

Comment (ShirleyNekoDev) [reply chunky/src/java/se/llbit/chunky/renderer/renderdump/ClassicDumpFormat.java:46]: Indeed 😅
