### PR TITLE
Fix saving of resource pack configuration

### LINKED ISSUE #1366: Chunky fails to save the new Resource Pack configuration as the new default in the latest snapshot.
In the latest snapshot, "saving" the new resource pack configuration as default is only temporary, and reverts to the previous configuration upon restarting of Chunky.

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
fixes #1366
also fixes missing path separator in deprecated method

### CODE REVIEW

**Review by Peregrine05 — APPROVED** [review]
I have tested these changes and saving of resource pack configurations now appears to work as it should.

File: lib/src/se/llbit/chunky/PersistentSettings.java [hunk 1]
```diff
@@ -110,9 +110,8 @@ private static void migrateOldSettings() {
     String lastTexturePack = settings.getString("lastTexturePack", null);
     if(lastTexturePack != null) {
       setLastTexturePack(lastTexturePack);
-      // TODO: remove setting with next release
-      // settings.removeSetting("lastTexturePack");
-      Log.info("migrated setting \"lastTexturePack\"");
+      // TODO: remove legacy setting with next release
```
Comment (ThatRedox) [inline lib/src/se/llbit/chunky/PersistentSettings.java:113]: Can we tag this with `2.6.0` so its easy to search through all the files to find everything we need to remove?
```suggestion
      // TODO: Remove legacy setting in 2.6.0
```

File: lib/src/se/llbit/chunky/PersistentSettings.java [hunk 2]
```diff
@@ -267,6 +266,8 @@ public static void setEnabledResourcePacks(File... enabledTexturePacks) {
       array.add(texturePackFile.toString());
     }
     settings.set("enabledResourcePacks", array);
+    // TODO: remove legacy setting with next release
```
Comment (ThatRedox) [inline lib/src/se/llbit/chunky/PersistentSettings.java:269]:
```suggestion
    // TODO: Remove legacy setting in 2.6.0
```

**Review by ThatRedox — APPROVED** [review]
