### PR TITLE
Try to locate javafx

### LINKED ISSUE #484: OpenJFX Issue arising again
Although I have 
`sudo apt install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (8u161-b12-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
I still get the error `Exception in thread "main" java.lang.NoClassDefFoundError: javafx/stage/Stage` when trying to `java -jar` either chunky or the launcher.

### LINKED ISSUE #523: Running Chunky with Java 11
same thing, java was 11, knocked down to 8, uninstalled/reinstalled openjfx in both versions...

---------------------------------\/- the stuff i get -\/-----------------

sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 

BEAST:~/Downloads$  java -jar ./ChunkyLauncher.jar --verbose
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -Dchunky.home=/home/drblackross/.chunky -classpath /home/drblackross/.chunky/lib/chunky-core-1.4.5.jar:/home/drblackross/.chunky/lib/commons-math3-3.2.jar se.llbit.chunky.main.Chunky
Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:214)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

Failed to launch Chunky. Command used:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -Dchunky.home=/home/drblackross/.chunky -classpath /home/drblackross/.chunky/lib/chunky-core-1.4.5.jar:/home/drblackross/.chunky/lib/commons-math3-3.2.jar se.llbit.chunky.main.Chunky

BEAST:~/Downloads$ sudo apt-get install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (11.0.2+1-1~18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

no matter what is done i still end up at...

BEAST:~/Downloads$  java -jar ./ChunkyLauncher.jar 
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:273)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:194)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

BEAST:~/Downloads$ sudo apt-get install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (11.0.2+1-1~18.04.2). <------ i don't think is an issue 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

------------------------------------------------------------------------------

i can run Chunky on windows 10,  yes... but it will only render a blue square at whatever size i choose as a output size in tiff or png lol

been using this tut, for the windows 10 system (didn't know about f3) 
https://chunky.llbit.se/your_first_render.html

my surface pro is the only windows 10 machine in my house (hell even the house is linux lol)

I haven't tried running chunky as root (but i shouldn't have too, right?).

sooooo this is where i am, i don't think its a new issue, but i'm willing to bet i am over looking something.

### PR DESCRIPTION
**Pull request by aTom3333**
Change the launcher so it tries to locate javafx in some predefined location (if you think of other locations, tell me).
If javafx is found, restart the launcher with javafx, else stop the launcher as usual but with an additional more descriptive error message.
This doesn't like a robust approach to the problem but I don't have a better idea for now. That's wy I would like some feedback/ideas during developpement.
Passing the argument to the invocation of chunky itself still need to be implemented.

Closes #523 
Closes #484

### CODE REVIEW

File: launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java [hunk 1]
```diff
@@ -61,150 +61,176 @@ protected static void launchFailure(String command) {
...
+       * If there are command line arguments then we assume that Chunky should run
+       * in headless mode, unless the --nolauncher command is present in which case
+       * we strip that and start regularly, but without launcher. The --launcher
+       * option overrides everything else and forces the launcher to appear.
+       */
 
-    boolean forceLauncher = false;
-    LaunchMode mode = LaunchMode.GUI;
-    String headlessOptions = "";
+      // TODO(llbit): the control flow for launching Chunky needs to be simplified.
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java:77]: I think we can drop this line. :smile:

File: launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java [hunk 2]
```diff
@@ -61,150 +61,176 @@ protected static void launchFailure(String command) {
...
+      String cause = e.getMessage();
+      if(cause.contains("javafx")) {
+        // Javafx error
+        if(retryIfMissingJavafx)
+          JavaFxLocator.retryWithJavafx(args);
+        System.err.println("Error: Java cannot find javafx.");
+        System.err.println("If you are using a JVM for java 11 or later, " +
+                "javafx is no longer shipped alongside and must be installed separately");
+        System.err.println("If you already have javafx installed, you need to run chunky with the command:");
+        System.err.println("java --module-path <path/to/javafx/lib> --add-modules javafx.controls,javafx.fxml -jar <path/to/ChunkyLauncher.jar>");
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java:231]: Can this message be displayed in some dialog so that it also pops up when not launching Chunky from CLI?

Comment (aTom3333) [reply launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java:231]: Probably using Swing?

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+              "/usr/share/openjfx/lib",
+              "/usr/lib/jvm/java-11-openjdk/lib",
+              "/usr/lib/jvm/java-12-openjdk/lib",
+              "/usr/lib/jvm/java-13-openjdk/lib",
+              "/usr/lib/jvm/java-14-openjdk/lib",
+              "/usr/lib/jvm/java-15-openjdk/lib",
+      };
+    } catch(URISyntaxException e) {
+      e.printStackTrace();
+      javafxPathCandidates1 = new String[0];
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:34]: The try…catch could be moved around `new File(ChunkyLauncher.class.getProtectionDomain().getCodeSource().getLocation().toURI())
                      .toPath().getParent().toAbsolutePath().toString() + File.separator + "lib", ` here to still use the other candidates. This isn't some hot code path, so you could probably use a `List<String>` to add the candidates dynamically.

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+    cmd.add("--module-path");
+    cmd.add(javafxDir.toAbsolutePath().toString());
+    cmd.add("--add-modules");
+    cmd.add("javafx.controls,javafx.fxml");
+
+    cmd.add("-cp");
+    cmd.add(ManagementFactory.getRuntimeMXBean().getClassPath());
+    cmd.add(ChunkyLauncher.class.getName());
+    cmd.addAll(Arrays.asList(args));
+    cmd.add("--noRetryJavafx"); // Make sure this doesn't end up as a fork bomb
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:61]: ot: For a proper fork bomb, launch the launcher at least twice in line 66

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+    } catch(IOException | InterruptedException e) {
+      e.printStackTrace();
+    }
+  }
+
+  public static void retryWithJavafx(String[] args) {
+    for(String candiate : javafxPathCandidates) {
+      Path directory = new File(candiate).toPath();
+      if(validJavafxDirectory(directory)) {
+        runWithJavafx(directory, args);
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:77]: Would this start multiple times if there are multiple candidates?

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+    cmd.add(ManagementFactory.getRuntimeMXBean().getClassPath());
+    cmd.add(ChunkyLauncher.class.getName());
+    cmd.addAll(Arrays.asList(args));
+    cmd.add("--noRetryJavafx"); // Make sure this doesn't end up as a fork bomb
+
+    ProcessBuilder builder = new ProcessBuilder(cmd);
+    builder.inheritIO();
+    try {
+      Process process = builder.start();
+      System.exit(process.waitFor());
```
Comment (leMaik) [inline launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:67]: Why wait for the subprocess?

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java (hunk 5 above)
Comment (aTom3333) [reply launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:77]: No, `runWithJavafx` doesn't return if it succeed at running a new process, it waits for the process to be other and the immediatly exit (to give the illusion that there was only one process to begin with)

File: launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java (hunk 2 above)
Comment (leMaik) [reply launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java:231]: `JOptionPane.showMessageDialog(null, "Oh no!")`?

File: launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java (hunk 6 above)
Comment (aTom3333) [reply launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java:67]: To give the illusion that there is only one process and because we want the output/error stream to be linked with the child streams (I don't know if the stream redirection still works if exiting immediatly)

**Review by leMaik — APPROVED** [review]
