### PR TITLE
Fix transparent sky not working with render regions.

### LINKED ISSUE #1725: Render regions and transparent sky
Doesn't seem to work: https://discord.com/channels/541221265512464394/1235574130347081780/1235595255039135804

### PR DESCRIPTION
**Pull request by leMaik**
Fixes #1725

### CODE REVIEW

File: chunky/src/java/se/llbit/chunky/renderer/scene/AlphaBuffer.java [hunk 1]
```diff
@@ -83,10 +87,10 @@ void computeAlpha(Scene scene, Type type, TaskTracker taskTracker) {
           state.ray = new Ray();
 
           for (int y = 0; y < height; y++) {
-            computeAlpha(scene, x, y, width, height, state);
+            computeAlpha(scene, x, y, cropX, cropY, width, height, fullWidth, fullHeight, state);
           }
 
-          task.update(width, done.incrementAndGet());
+          task.update(height, done.incrementAndGet());
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/renderer/scene/AlphaBuffer.java:93]: Oh... This should be `width`
