### PR TITLE
Fix initial text overflow for labeled text fields by scrolling to the end

### LINKED ISSUE #1378: Initial formatting of some input fields has incorrect formatting
https://user-images.githubusercontent.com/16853282/180037678-4fc3f41c-053f-4ebd-be3d-195b5e9fce7c.mp4

Seems to only happen for text that is longer than the size of the box at initialisation

### PR DESCRIPTION
**Pull request by ShirleyNekoDev**
fixes #1378 (best effort: is better now, but not perfect)

### CODE REVIEW

File: chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java [hunk 1]
```diff
@@ -70,6 +72,16 @@ public void setTextField(TextField textField) {
...
   }
 
+  /**
+   * scrolls to the end of the text field
+   * _best effort_ fix for 1378 - long initial text overflows the text field (cut off)
+   */
+  private void fixTextPositionOffset() {
+    TextField textField = textFieldProperty.get();
+    if (!textField.isFocused())
+      textField.end();
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java:82]:
```suggestion
    if (!textField.isFocused()) {
      textField.end();
    }
```

**Review by leMaik — APPROVED** [review]
