### PR TITLE
Fix skymap bugs due to synchronization issues

### LINKED ISSUE #825: Black bars & colored pixels in sky
In both preview and in render, black bars and boxes appear in the sky. Seems to only apply for SPP 1, and becomes normal after that, so high SPP normalizes it out to the correct sky color. Also seems to depend greatly on canvas size. This is happening on both Preetham as well as Nishita.

Example on Preetham in both preview and rendered:

Screenshot 2021-02-20 at 07 19 48_5

This might have to do with the sky stuff that @alexhliu has been working on.

Tested on commit 209fd07.

### PR DESCRIPTION
**Pull request by leMaik**
First I fixed the synchronization but then I just made it obsolete. Check it commit-by-commit to see the history.

@alexhliu Can't select you as a reviewer but your feedback is much appreciated :raised_hands: 

Fixes #825

### CODE REVIEW

File: chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java [hunk 1]
```diff
@@ -106,44 +119,42 @@ public Vector3 calcIncidentLight(Ray ray) {
...
+    double phi = ((double) y / skyResolution) * PI - PI / 2;
     double r = FastMath.cos(phi);
     ray.d.set(FastMath.cos(theta) * r, FastMath.sin(phi), FastMath.sin(theta) * r);
 
     Vector3 color = simSky.calcIncidentLight(ray);
     ColorUtil.RGBtoHSL(color, color.x, color.y, color.z);
-    skyTexture[x][y][0] = color.x;
-    skyTexture[x][y][1] = color.y;
-    skyTexture[x][y][2] = color.z;
+    return color;
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java:158]: By not writing to `skyTexture` here, this method doesn't need to be synchronized anymore and can be used concurrently.

File: chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java [hunk 2]
```diff
@@ -16,88 +16,101 @@
...
 
+  public void setSimulatedSkyMode(SimulatedSky skyMode) {
+    this.simSky = skyMode;
+    precalculateSky();
+  }
+
   /**
-   * Calculate the incident light. Will automatically pull from the cache or calculate new values. Cache values are
-   * bilinearly interpolated.
+   * Calculate the incident light. Will automatically pull from the cache or calculate new values.
```
Comment (alexhliu) [inline chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java:106]: Might want to remove `or calculate new values` since the cache is now pregenerated.

File: chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java [hunk 3]
```diff
@@ -16,88 +16,101 @@
...
   /**
-   * An on-the-fly sky cache. Automatically calculates sky colors as they are requested and caches them. Any repeat
-   * requests will pull from the cache.
-   *
-   * Default cache size is 1024x1024 with bilinear interpolation which seems to work well for all simulated sky
-   * modes.
+   * An on-the-fly sky cache. Automatically calculates sky colors as they are requested and caches
+   * them. Any repeat requests will pull from the cache.
+   * <p>
+   * Default cache size is 1024x1024 with bilinear interpolation which seems to work well for all
```
Comment (alexhliu) [inline chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java:44]: Might want to change this to the correct value of `128x128` for anyone reading the javadocs.

Comment (alexhliu) [reply chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java:44]: And maybe remove `on-the-fly` and mention that it is precalculated on creation and reset do discourage needlessly resetting it.

**Review by alexhliu — COMMENTED** [review]
Looks good 👍. You might want to update the javadocs a bit to make the precalculation more clear to discourage future contributors from needlessly resetting the skyCache.
