### PR TITLE
Add a `Sky exposure` control, fix the `Draw sun` control disabling sunlight, and add few new sun controls

### LINKED ISSUE #54: Sun radius control
Add option to the Render Controls dialog to change the sun radius.

### LINKED ISSUE #1317: Disabling `Draw sun` disables sunlight in the latest snapshot
In the latest snapshot, disabling `Draw sun` when SSS is set to Fast, High quality, or Off causes the sunlight to be completely disabled. This should not occur, as `Draw sun` is only to change the visibility of the texture of the sun on the sky. There is already a setting to disable sunlight, which is SSS: NON_LUMINOUS.

### LINKED ISSUE #1471: Changing `Apparent sky brightness` changes the apparent brightness of the sun texture
This is only apparent in the path-traced render, and not in the preview. Ideally, this should not happen.

### LINKED ISSUE #1472: Independent skymap exposure control
Different skymaps, mainly HDRi's, have vastly different brightness levels. There are a few benefits when it comes to memory usage and performance when it comes to using pngs vs HDRi's.

png varient 16SPP:
image

HDRi varient 16SPP:
image

In the case you wish to switch from png to HDRi, or HDRi to HDRi, and you do not wish to alter your settings too much... you can't. Opposed to having a single control which can be used to alter how the changed element interacts with the scene you are required to edit multiple:

`Sky brightness`, `Apparent sky brightness`, `Emitter intensity`, `Sun intensity`, `Sun luminosity`, `Exposure`.

Each of those settings have knock-on effects which take time to iron out.

He's an example HDRi:
image

This is a crude "fix" by just adjusting the exposure:
image

You would still need to re-adjust all the other settings.

---

Having a single control that can be used to quickly adjust the exposure, both brightness and apparent, of just the skymap would increase flexibility and reduce time spent tweaking all the ~~spaghetti~~ various interconnected settings.

---

Related to #1471

### PR DESCRIPTION
**Pull request by Peregrine05**
Fixes #1471.
Fixes #1472.
Fixes #1317.
Closes #54.

- Added a `Sky exposure` control, which changes both the sky brightness and the apparent sky brightness.
- The controls `Sky brightness` and `Apparent sky brightness` modify the values separately.
- Fixed `Apparent sky brightness` changing the apparent brightness of the sun in the path-traced render.
- Added an `Apparent sun brightness` control, which changes the apparent brightness of the texture of the sun. `Sun Intensity` and `Sun Luminosity` no longer change the apparent brightness of the sun.
- Fixed `Draw sun` disabling sunlight.
- Added `Modify sun texture by color`, which changes whether `Apparent sun color` has an effect on the texture of the sun.
- Added `Apparent sun color`, which has an effect on the sun texture if `Modify sun texture by color is enabled.
- Added a `Sun radius` control.

**GUI:**
image

**Sunlight works with `Draw sun` disabled:**
image

**Sun color is unchanged when `Modify sun texture by color` is disabled:**
image

**Custom sun color modifier specified by `Apparent sun color` used when `Modify sun texture by color` is enabled:**
**`Sun radius`: 10:**
image

### CODE REVIEW

**Comment by jackjt8** [comment]
Old
normal

`Modify sun texture by color` - Subtle but honestly adds so much
modify

File: chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java [hunk 1]
```diff
@@ -360,11 +445,19 @@ public void getRandomSunDirection(Ray reflected, Random random) {
...
     sun.add("luminosity", luminosity);
+    sun.add("apparentBrightness", apparentBrightness);
+    sun.add("radius", radius);
+    sun.add("modifySunTexture", enableTextureModification);
     JsonObject colorObj = new JsonObject();
     colorObj.add("red", color.x);
     colorObj.add("green", color.y);
     colorObj.add("blue", color.z);
     sun.add("color", colorObj);
+    JsonObject apparentColorObj = new JsonObject();
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java:456]: This should serialize colors as in other places (eg. sky or water color).

File: chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java [hunk 2]
```diff
@@ -394,6 +497,10 @@ public Vector3 getColor() {
     return new Vector3(color);
   }
 
+  public Vector3 getApparentColor() {
+    return new Vector3(apparentColor);
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java:501]: Instead of returning copies every time, could we let the consumer copy this vector as needed?

Comment (leMaik) [reply chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java:501]: Same for the existing `getColor`, we might be able to improve that.

File: chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java [hunk 3]
```diff
@@ -101,6 +114,13 @@ public LightingTab() throws IOException {
             (observable, oldValue, newValue) -> scene.setSunSamplingStrategy(newValue));
     sunSamplingStrategy.setTooltip(new Tooltip("Determine how the sun is sampled at each bounce."));
 
+    apparentSunBrightness.setName("Apparent sun brightness");
+    apparentSunBrightness.setTooltip("Apparent brightness of the sun texture");
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java:118]: The wording of the tooltips is inconsistent (modifies xy vs. xy), but that might as well be another PR.

File: chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java [hunk 4]
```diff
@@ -129,6 +149,21 @@ public LightingTab() throws IOException {
...
+    modifySunTexture.selectedProperty().addListener((observable, oldValue, newValue) -> {
+      scene.sun().setEnableTextureModification(newValue);
+      apparentSunColor.setDisable(!newValue);
+    });
+
+    apparentSunColor.setDisable(true);
+    apparentSunColor.colorProperty().addListener(apparentSunColorListener);
+
+    sunRadius.setName("Sun radius");
+    sunRadius.setTooltip("Radius of the sun");
```
Comment (leMaik) [inline chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java:162]: Maybe "size" to explain radius? Do we need this tool tip?

**Review by leMaik — APPROVED** [review]
Great work! 👍 Just some really minor things.

File: chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java (hunk 4 above)
Comment (Peregrine05) [reply chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java]: I changed the name to `Sun size`, which is self explanatory. I'll remove the tooltip.

File: chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java (hunk 3 above)
Comment (Peregrine05) [reply chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java]: I changed the tooltips to be of the same style ("does this").

File: chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java (hunk 1 above)
Comment (leMaik) [reply chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java:462]: Turns out it does, nevermind my comment.

**Review by leMaik — APPROVED** [review]
