### PR TITLE
Fix pressed pressure plates, observer and attached tripwire block models.

### LINKED ISSUE #881: 21w13a
Not many new features at this time but a lot of model updates (mostly uv mapping tweaks). We'll have to see how we can implement the light block (help wanted).

- [x] Light block

Updated block models (may or may not require changes in Chunky):
- [x] Big dripleaf
- [x] Chain
- [x] Crops (carrot, wheat, ...)
- [x] Sea pickles (all variants)
- [x] Glow lichen
- [x] Ladder
- [x] Lightning rod
- [x] Powder snow (I'm not sure if it is implemented correctly in Chunky right now)
- [x] Small dripleaf
- [x] Stonecutter
- [x] Azalea
- [x] Lantern
- [x] Tripwire
- [ ] Attached tripwire
- [x] Tripwire hook
- [x] Vine

### PR DESCRIPTION
**Pull request by leMaik**
Fixes #881 
Related to #888

### CODE REVIEW

File: chunky/src/java/se/llbit/chunky/model/minecraft/TripwireModel.java [hunk 1]
```diff
@@ -18,380 +18,692 @@
...
+  };
 
   private final Quad[] quads;
   private final Texture[] textures;
 
-  public TripwireModel(int connections) {
-    quads = model[connections];
+  public TripwireModel(boolean attached, boolean north, boolean south, boolean east, boolean west) {
+    int nsew = (north ? 1 : 0) << 3 | (south ? 1 : 0) << 2 | (east ? 1 : 0) << 1 | (west ? 1 : 0);
+    if (attached) {
```
Comment (ThatRedox) [inline chunky/src/java/se/llbit/chunky/model/minecraft/TripwireModel.java:666]: Maybe something like:
```java
Quad[] baseNS, baseN, ...;
if (attached) {
  baseNS = tripwireAttachedNS;
  baseN = tripwireAttachedN;
  <...>
} else {
  baseNS = tripwireNS;
  baseN = tripwireN;
  <...>
}

quads = switch (nsew) {
    case 0b0000 -> baseNS;
    case 0b0001 -> Model.rotateNegY(baseN);
```
would be a cleaner way of implementing this?
